"""The BUILD_SPEC 6 robustness matrix.

The brief asks that one malformed file not fail the batch. The standard built to
is stronger: **nothing crashes, ever**. Every case below must either produce
schema-valid output or a clean `status="failed"` with a reason -- never an
unhandled exception, and never a partially-populated result.

These run on the DSP-only stack by default so they are fast and need no model
downloads; the isolation being tested lives in `pipeline.py`, above the models.
"""
from __future__ import annotations

import json

import pytest

from voicetone import FileResult, analyze_file
from voicetone.schema import FIELDS, CallAnalysis
from voicetone.stack import build_predictors

STACK = "vad,quality,noise"


def _run(path) -> FileResult:
    return analyze_file(path, list(build_predictors(STACK)))


def _assert_wellformed(r: FileResult) -> None:
    """Either a clean failure with a reason, or output that validates."""
    assert r.status in ("ok", "failed")
    if r.status == "failed":
        assert r.error, "a failed file must say why"
        assert r.result is None
        return
    assert r.result is not None
    assert set(r.result) == set(FIELDS), "output must carry exactly the schema"
    CallAnalysis(**r.result)                       # revalidates every rule
    json.dumps(r.result)                           # must be serialisable
    assert 0.0 <= r.result["confidence"] <= 1.0


# --------------------------------------------------------------------------
# structurally invalid input -> clean failure
# --------------------------------------------------------------------------

def test_zero_byte_file(broken):
    r = _run(broken["zero_byte"])
    assert r.status == "failed"
    assert "zero" in r.error.lower() or "ffprobe" in r.error.lower()
    _assert_wellformed(r)


def test_text_file_with_audio_extension(broken):
    r = _run(broken["text_as_wav"])
    assert r.status == "failed"
    _assert_wellformed(r)


def test_truncated_file(broken):
    if "truncated" not in broken:
        pytest.skip("samples not present")
    _assert_wellformed(_run(broken["truncated"]))    # may decode or fail; not crash


def test_missing_file():
    r = _run("/nonexistent/nope.wav")
    assert r.status == "failed"
    _assert_wellformed(r)


def test_unsupported_extension(tmp_path):
    p = tmp_path / "notes.txt"
    p.write_text("hello")
    r = _run(p)
    assert r.status == "failed"
    assert "unsupported" in r.error.lower()


# --------------------------------------------------------------------------
# valid audio, awkward content -> valid output
# --------------------------------------------------------------------------

@pytest.mark.parametrize("key", [
    "pure_silence", "white_noise", "clip_half_second", "square_wave",
    "dtmf", "hold_music",
])
def test_awkward_content_produces_valid_output(broken, key):
    r = _run(broken[key])
    assert r.status == "ok", f"{key} should decode: {r.error}"
    _assert_wellformed(r)


def test_pure_silence_reports_long_silence(broken):
    r = _run(broken["pure_silence"])
    assert r.result["long_silence_present"] is True
    assert r.result["confidence"] < 0.75, "no evidence should mean low confidence"


def test_white_noise_has_no_speech_and_low_confidence(broken):
    r = _run(broken["white_noise"])
    assert r.latents["speech_ratio"] == 0.0
    assert r.result["confidence"] < 0.8


def test_square_wave_is_impaired(broken):
    """A fully-clipped signal must not come back `clear`."""
    r = _run(broken["square_wave"])
    assert r.result["audio_quality"] in ("slightly_impaired", "severely_impaired")


def test_half_second_clip_does_not_crash(broken):
    _assert_wellformed(_run(broken["clip_half_second"]))


# --------------------------------------------------------------------------
# format and channel variations
# --------------------------------------------------------------------------

@pytest.mark.parametrize("key", ["mulaw_8k", "surround_5_1", "true_stereo",
                                 "video_container", "unicode_name"])
def test_format_variations(broken, key):
    if key not in broken:
        pytest.skip(f"{key} could not be generated by this ffmpeg build")
    r = _run(broken[key])
    assert r.status == "ok", f"{key} should decode: {r.error}"
    _assert_wellformed(r)


def test_8k_mulaw_is_band_limited(broken):
    if "mulaw_8k" not in broken:
        pytest.skip("no mulaw fixture")
    r = _run(broken["mulaw_8k"])
    # Telephony band-limiting is a real if mild impairment (BUILD_SPEC 6).
    assert r.result["audio_quality"] in ("clear", "slightly_impaired")
    assert r.latents["quality_detail"]["native_sr"] == 8000.0


def test_true_stereo_is_detected_as_dual_channel(broken):
    if "true_stereo" not in broken:
        pytest.skip("no stereo fixture")
    from voicetone import load
    ctx = load(broken["true_stereo"])
    assert ctx.true_stereo, "genuinely different channels must not be downmixed blindly"


def test_fake_stereo_is_detected(samples):
    """The provided calls are a mono downmix in a stereo container."""
    if not samples:
        pytest.skip("samples not present")
    from voicetone import load
    ctx = load(samples[0])
    assert ctx.n_channels == 2
    assert not ctx.true_stereo
    assert ctx.channel_corr > 0.98


def test_unicode_filename_is_preserved_exactly(broken):
    if "unicode_name" not in broken:
        pytest.skip("no unicode fixture")
    src = broken["unicode_name"]
    r = _run(src)
    assert r.name == src.name, "the original filename must survive verbatim"
    assert "✅" in r.name and "📞" in r.name


# --------------------------------------------------------------------------
# batch-level isolation
# --------------------------------------------------------------------------

def test_one_bad_file_does_not_kill_the_batch(broken, samples):
    from voicetone import analyze_batch
    if not samples:
        pytest.skip("samples not present")
    paths = [broken["zero_byte"], samples[0], broken["text_as_wav"]]
    results = analyze_batch(paths, list(build_predictors(STACK)))
    assert len(results) == 3
    assert results[1].status == "ok"
    assert sum(r.status == "failed" for r in results) == 2
    for r in results:
        _assert_wellformed(r)


def test_a_failing_predictor_is_skipped_not_fatal(samples):
    """Predictor-level isolation: one broken stage must not lose the file."""
    if not samples:
        pytest.skip("samples not present")

    class Exploding:
        name = "exploding"

        def __call__(self, ctx, lat):
            raise RuntimeError("boom")

    r = analyze_file(samples[0], [Exploding(), *build_predictors(STACK)])
    assert r.status == "ok"
    assert any("exploding" in w for w in r.warnings)
    _assert_wellformed(r)
